### ISSUE TITLE
Links broken with recent re-organization

### ISSUE THREAD

**Issue by jeremiah** [OpenChain-Project/Reference-Material#5]
Links like https://www.openchainproject.org/news/2017/09/13/fsfe-contributes-reuse-guide-to-openchain-curriculum hold URLs, like; https://github.com/OpenChain-Project/curriculum/blob/master/guides/Reuse-for-OpenChain.md which now no longer work due to recent repo reorganization.

**Comment by theopenchainproject** [comment]
Thanks for flagging. We are currently doing a reorg in preparation for the ISO/IEC publication because the library was sprawling and not internally consistent. The reference library page will be updated over the weekend:
https://www.openchainproject.org/resources
Old news posts will be reviewed and addressed by admin staff, with a priority on newer material first. Page visit analysis shows a signifiant drop on readership for older material with the significant majority of views going to the reference library itself.

**Comment by theopenchainproject** [comment]
Closing as issue is known and process underway to address.
